#!/usr/bin/env bash
# Standalone installer for bazel-aws-maven-proxy.
#
# Usage:
#   curl -sL https://raw.githubusercontent.com/rp-arielrodriguez/bazel-aws-maven-proxy/main/scripts/install.sh | bash
#
# Or with a custom install directory:
#   curl -sL .../install.sh | INSTALL_DIR=~/dev/bazel-proxy bash
#
# Or shim-only mode (for upgrades):
#   bash scripts/install.sh --shim-only
#
# What it does:
#   1. Checks prerequisites (git, mise, aws, podman/docker)
#   2. Clones the repo (or updates if already cloned)
#   3. Runs mise run setup (interactive wizard)
#   4. Creates a global 'bazel-proxy' command in ~/.local/bin
#
# The global command lets you operate from anywhere:
#   bazel-proxy start|stop|status|login|logs|upgrade|...
set -euo pipefail

# Parse flags
SHIM_ONLY=false
for arg in "$@"; do
  case "$arg" in
    --shim-only) SHIM_ONLY=true ;;
  esac
done

REPO_URL="${REPO_URL:-https://github.com/rp-arielrodriguez/bazel-aws-maven-proxy.git}"
INSTALL_DIR="${INSTALL_DIR:-$HOME/.local/share/bazel-proxy}"
BIN_DIR="${BIN_DIR:-$HOME/.local/bin}"
SHIM_NAME="bazel-proxy"

# Colors (if terminal supports them)
if [ -t 1 ]; then
  RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; BOLD='\033[1m'; NC='\033[0m'
else
  RED=''; GREEN=''; YELLOW=''; BOLD=''; NC=''
fi

info()  { printf "${BOLD}%s${NC}\n" "$*"; }
ok()    { printf "${GREEN}✓${NC} %s\n" "$*"; }
warn()  { printf "${YELLOW}⚠${NC} %s\n" "$*"; }
fail()  { printf "${RED}✗${NC} %s\n" "$*"; exit 1; }

# Function to generate shim (used by both full install and --shim-only)
generate_shim() {
  local REPO_DIR="$1"
  cd "$REPO_DIR"
  
  info "Installing global command..."
  mkdir -p "$BIN_DIR"
  
  cat > "$BIN_DIR/$SHIM_NAME" << 'SHIM_EOF'
#!/usr/bin/env bash
# bazel-proxy: global shim for bazel-aws-maven-proxy
# Auto-generated by install.sh — do not edit manually.
# SHIM_VERSION: {{SHIM_VERSION}}
set -euo pipefail

INSTALL_DIR="{{INSTALL_DIR}}"

if [ ! -d "$INSTALL_DIR" ]; then
  echo "Error: installation not found at $INSTALL_DIR" >&2
  echo "Re-install with: curl -sL https://raw.githubusercontent.com/rp-arielrodriguez/bazel-aws-maven-proxy/main/scripts/install.sh | bash" >&2
  exit 1
fi

cd "$INSTALL_DIR"

CMD="${1:-help}"
shift 2>/dev/null || true

case "$CMD" in
  start|stop|setup|uninstall|upgrade|config)
    exec mise run "$CMD" "$@" ;;
  status)
    exec mise run status "$@" ;;
  sso-status)
    exec mise run sso-status "$@" ;;
  login)
    exec mise run sso-login "$@" ;;
  logout)
    exec mise run sso-logout "$@" ;;
  logs)
    exec bash "$INSTALL_DIR/scripts/logs.sh" "$@" ;;
  mode)
    exec mise run sso-mode "$@" ;;
  mode:*)
    exec mise run "sso-$CMD" "$@" ;;
  install)
    exec mise run sso-install "$@" ;;
  restart)
    exec mise run sso-restart "$@" ;;
  clean)
    exec mise run sso-clean "$@" ;;
  clean:cookies)
    exec mise run sso-clean:cookies "$@" ;;
  check-update)
    exec mise run check-update "$@" ;;
  containers:*)
    exec mise run "$CMD" "$@" ;;
  config:set)
    exec mise run config:set "$@" ;;
  tls-skip:*)
    exec mise run "$CMD" "$@" ;;
  help|-h|--help)
    echo "bazel-proxy — manage Bazel AWS Maven S3 proxy"
    echo ""
    echo "System:"
    echo "  start              Start everything (native mode: proxy + monitor + watcher)"
    echo "  stop               Stop everything"
    echo "  status             System status: native/container mode, processes"
    echo "  setup              Re-run interactive setup"
    echo "  upgrade            Smart upgrade (pull + selective rebuild)"
    echo "  check-update       Check if updates available"
    echo "  uninstall          Uninstall everything"
    echo ""
    echo "SSO:"
    echo "  login              Trigger SSO login"
    echo "  logout             Invalidate credentials, trigger renewal"
    echo "  logs [OPTIONS]     Show logs (default: SSO watcher)"
    echo "    --all, --s3proxy, --monitor, --sso  Filter logs"
    echo "    --follow, --tail N                  Output control"
    echo "    --native, --container               Mode override"
    echo "  mode               Show current watcher mode"
    echo "  mode:notify|auto|silent|standalone"
    echo "                     Switch watcher mode"
    echo "  sso-status         SSO watcher status: running, mode, credentials"
    echo "  restart            Restart watcher"
    echo "  install            Reinstall watcher (rebuild webview + daemon)"
    echo "  clean              Clear state/signals/cooldown"
    echo "  clean:cookies      Clear webview cookies"
    echo ""
    echo "Containers (alternative to native mode):"
    echo "  containers:up      Start containers"
    echo "  containers:down    Stop containers"
    echo "  containers:restart Restart containers"
    echo ""
    echo "Config:"
    echo "  config             Show current configuration"
    echo "  config:set K=V     Update configuration"
    echo "  tls-skip:enable    Enable TLS skip"
    echo "  tls-skip:disable   Disable TLS skip"
    ;;
  *)
    echo "Unknown command: $CMD" >&2
    echo "Run 'bazel-proxy help' for usage" >&2
    exit 1
    ;;
esac
SHIM_EOF

  # Inject the actual install directory and version into the shim
  SHIM_VERSION=$(cd "$REPO_DIR" && git rev-parse --short HEAD 2>/dev/null || echo "dev")
  sed -i.bak "s|{{INSTALL_DIR}}|$INSTALL_DIR|g; s|{{SHIM_VERSION}}|$SHIM_VERSION|g" "$BIN_DIR/$SHIM_NAME" && rm -f "$BIN_DIR/$SHIM_NAME.bak"
  chmod +x "$BIN_DIR/$SHIM_NAME"
  ok "Installed: $BIN_DIR/$SHIM_NAME"
  
  # Check if BIN_DIR is in PATH
  if ! echo "$PATH" | tr ':' '\n' | grep -qx "$BIN_DIR"; then
    echo ""
    warn "$BIN_DIR is not in your PATH"
    echo "  Add to your shell profile:"
    echo "    export PATH=\"$BIN_DIR:\$PATH\""
  fi
}

# Shim-only mode: skip everything except shim regeneration
if $SHIM_ONLY; then
  if [ ! -d "$INSTALL_DIR" ]; then
    echo "Error: installation not found at $INSTALL_DIR" >&2
    echo "Run full install first: curl -sL https://raw.githubusercontent.com/rp-arielrodriguez/bazel-aws-maven-proxy/main/scripts/install.sh | bash" >&2
    exit 1
  fi
  generate_shim "$INSTALL_DIR"
  exit 0
fi

# Detect existing old-style installation and migrate
OLD_INSTALL="$HOME/.bazel-aws-maven-proxy"
if [ -z "${INSTALL_DIR+override}" ] && [ -d "$OLD_INSTALL/.git" ]; then
  echo "Found existing installation at $OLD_INSTALL"
  echo "Migrating to $INSTALL_DIR..."
  mkdir -p "$(dirname "$INSTALL_DIR")"
  mv "$OLD_INSTALL" "$INSTALL_DIR"
  echo "✓ Migrated"
fi

# ---- Prerequisites ----
info "Checking prerequisites..."

command -v git &>/dev/null  || fail "git not found. Install Xcode CLT: xcode-select --install"
command -v mise &>/dev/null || fail "mise not found. Install: brew install mise"
command -v aws &>/dev/null  || fail "aws CLI not found. Install: brew install awscli"

if command -v podman &>/dev/null; then
  ok "podman"
elif command -v docker &>/dev/null; then
  ok "docker"
else
  fail "No container engine found. Install podman (brew install podman) or docker."
fi

ok "Prerequisites met"
echo ""

# ---- Clone or update ----
if [ -d "$INSTALL_DIR/.git" ]; then
  info "Existing installation found at $INSTALL_DIR"
  cd "$INSTALL_DIR"
  CURRENT=$(git rev-parse --short HEAD)
  git pull --ff-only origin main 2>/dev/null && ok "Updated (was $CURRENT)" || warn "Pull failed — using existing code"
else
  info "Cloning to $INSTALL_DIR..."
  mkdir -p "$(dirname "$INSTALL_DIR")"
  git clone "$REPO_URL" "$INSTALL_DIR"
  cd "$INSTALL_DIR"
  ok "Cloned"
fi
echo ""

# ---- Install tools ----
info "Installing tools via mise..."
# Trust the config so mise doesn't reject it in a new clone
mise trust --yes 2>/dev/null || mise trust 2>/dev/null || true
mise install --yes 2>&1 | tail -1
ok "Tools ready"
echo ""

# ---- Run setup (interactive) ----
# When piped (curl | bash), stdin is the script itself, not the terminal.
# Redirect stdin from /dev/tty so setup.py can read user input.
info "Running interactive setup..."
echo ""
if [ -t 0 ]; then
  # Already have a terminal — run normally
  mise run setup
elif (echo >/dev/tty) 2>/dev/null; then
  # Piped context (curl | bash) — reconnect stdin to terminal
  mise run setup </dev/tty
else
  # No terminal available at all (CI, SSH without TTY, etc.)
  warn "No terminal available — setup requires interactive input."
  echo "  Run setup manually: cd $INSTALL_DIR && mise run setup"
  echo ""
fi

# ---- Create global shim ----
generate_shim "$INSTALL_DIR"

echo ""
info "Installation complete!"
echo ""
echo "  From anywhere:  bazel-proxy start"
echo "  From repo dir:  mise run start"
echo ""
echo "  System status:  bazel-proxy status"
echo "  SSO status:     bazel-proxy sso-status"
echo "  Help:           bazel-proxy help"
